// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAnV7TG8XoajP1WMMsiJ-yd3GoumGzAhQ',
    appId: '1:898886820254:web:1ed9d78c97e205abffb68f',
    messagingSenderId: '898886820254',
    projectId: 'psychbeing-ce6f7',
    authDomain: 'psychbeing-ce6f7.firebaseapp.com',
    storageBucket: 'psychbeing-ce6f7.appspot.com',
    measurementId: 'G-PLSLTGEE21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJOhP4u43DWYTR7DEgLwlcL6LIUjQWAio',
    appId: '1:898886820254:android:0c52098faf3908acffb68f',
    messagingSenderId: '898886820254',
    projectId: 'psychbeing-ce6f7',
    storageBucket: 'psychbeing-ce6f7.appspot.com',
  );
}
